version: "3.9"

services:
  web:
    build:
      context: "Vue"
    container_name: "lego-collectors-web-container"
    ports:
      - "80:80"
  api:
    build:
      context: LegoCollectors.WebAPI
    container_name: "lego-collectors-api-container"
    ports:
      - "5000:80"